import 'package:lawyer_app/src/models/lawyer_model/lawyer_model.dart';

final List<LawyerModel> dummyLawyers = [
  LawyerModel(
    id: 1,
    firstName: "Sarah",
    lastName: "Khan",
    category: "Criminal Law",
    phone: "+92 300 1234567",
    email: "sarah.khan@example.com",
    biography:
        "Sarah Khan is an experienced criminal lawyer with over 10 years of courtroom experience. She has successfully defended numerous high-profile cases.",
    description:
        "Dedicated and passionate about justice, Sarah ensures every client receives fair representation.",
    rating: 4.8,
    reviews: 152,
    profilePhoto: "https://randomuser.me/api/portraits/women/44.jpg",
  ),
  LawyerModel(
    id: 2,
    firstName: "Ali",
    lastName: "Raza",
    category: "Corporate Law",
    phone: "+92 312 9876543",
    email: "ali.raza@example.com",
    biography:
        "Ali Raza specializes in corporate and tax law, offering strategic legal advice to major firms and startups alike.",
    description: "Focused on helping businesses navigate legal complexities efficiently.",
    rating: 4.6,
    reviews: 98,
    profilePhoto: "https://randomuser.me/api/portraits/men/32.jpg",
  ),
  LawyerModel(
    id: 3,
    firstName: "Hina",
    lastName: "Malik",
    category: "Family Law",
    phone: "+92 333 1112233",
    email: "hina.malik@example.com",
    biography:
        "Hina Malik provides compassionate and effective legal assistance in family disputes and divorce settlements.",
    description: "Committed to resolving conflicts through understanding and professionalism.",
    rating: 4.9,
    reviews: 204,
    profilePhoto: "https://randomuser.me/api/portraits/women/65.jpg",
  ),
  LawyerModel(
    id: 4,
    firstName: "Ahmed",
    lastName: "Butt",
    category: "Immigration Law",
    phone: "+92 345 6677889",
    email: "ahmed.butt@example.com",
    biography:
        "Ahmed Butt is a leading immigration lawyer, helping clients with visa applications and residency issues.",
    description: "Ensuring smooth immigration processes with personalized guidance.",
    rating: 4.7,
    reviews: 120,
    profilePhoto: "https://randomuser.me/api/portraits/men/41.jpg",
  ),
  LawyerModel(
    id: 5,
    firstName: "Nimra",
    lastName: "Ali",
    category: "Intellectual Property",
    phone: "+92 321 9988776",
    email: "nimra.ali@example.com",
    biography:
        "Nimra Ali assists startups and creators in protecting their intellectual property rights globally.",
    description: "Innovative legal thinker focused on empowering clients through smart legal solutions.",
    rating: 4.5,
    reviews: 89,
    profilePhoto: "https://randomuser.me/api/portraits/women/33.jpg",
  ),
  LawyerModel(
    id: 6,
    firstName: "Bilal",
    lastName: "Sheikh",
    category: "Civil Law",
    phone: "+92 301 1122334",
    email: "bilal.sheikh@example.com",
    biography:
        "Bilal Sheikh handles property and civil disputes with a strong focus on settlements and legal mediation.",
    description: "Expert in real estate law and civil litigation.",
    rating: 4.4,
    reviews: 77,
    profilePhoto: "https://randomuser.me/api/portraits/men/27.jpg",
  ),
  LawyerModel(
    id: 7,
    firstName: "Mehwish",
    lastName: "Zafar",
    category: "Corporate Law",
    phone: "+92 320 1237788",
    email: "mehwish.zafar@example.com",
    biography:
        "Mehwish Zafar offers comprehensive legal guidance in employment and business-related matters.",
    description: "Helping organizations and employees maintain fair work practices.",
    rating: 4.7,
    reviews: 142,
    profilePhoto: "https://randomuser.me/api/portraits/women/56.jpg",
  ),
  LawyerModel(
    id: 8,
    firstName: "Hassan",
    lastName: "Iqbal",
    category: "Cyber Law",
    phone: "+92 334 4442233",
    email: "hassan.iqbal@example.com",
    biography:
        "Hassan Iqbal is a tech-savvy lawyer focusing on cybercrime cases, online fraud, and digital privacy.",
    description: "Protecting clients in the digital era through modern legal expertise.",
    rating: 4.8,
    reviews: 188,
    profilePhoto: "https://randomuser.me/api/portraits/men/37.jpg",
  ),
  LawyerModel(
    id: 9,
    firstName: "Ayesha",
    lastName: "Tariq",
    category: "Environmental Law",
    phone: "+92 335 9988775",
    email: "ayesha.tariq@example.com",
    biography:
        "Ayesha Tariq advocates for environmental justice, helping organizations comply with sustainability laws.",
    description: "Championing eco-friendly legal practices across industries.",
    rating: 4.6,
    reviews: 92,
    profilePhoto: "https://randomuser.me/api/portraits/women/26.jpg",
  ),
  LawyerModel(
    id: 10,
    firstName: "Usman",
    lastName: "Farooq",
    category: "Tax Law",
    phone: "+92 336 8877665",
    email: "usman.farooq@example.com",
    biography:
        "Usman Farooq specializes in tax disputes and audits, providing efficient legal tax solutions.",
    description: "Helping clients minimize tax liabilities within legal frameworks.",
    rating: 4.5,
    reviews: 81,
    profilePhoto: "https://randomuser.me/api/portraits/men/12.jpg",
  ),
  LawyerModel(
    id: 11,
    firstName: "Fatima",
    lastName: "Javed",
    category: "Criminal Law",
    phone: "+92 345 9988223",
    email: "fatima.javed@example.com",
    biography:
        "Fatima Javed is known for her fearless representation in criminal defense cases across major cities.",
    description: "Relentless advocate for justice and fairness.",
    rating: 4.9,
    reviews: 230,
    profilePhoto: "https://randomuser.me/api/portraits/women/22.jpg",
  ),
  LawyerModel(
    id: 12,
    firstName: "Zain",
    lastName: "Haider",
    category: "Corporate Law",
    phone: "+92 331 7778899",
    email: "zain.haider@example.com",
    biography:
        "Zain Haider advises companies on mergers, acquisitions, and corporate governance.",
    description: "Delivering strategic corporate law solutions.",
    rating: 4.7,
    reviews: 108,
    profilePhoto: "https://randomuser.me/api/portraits/men/44.jpg",
  ),
  LawyerModel(
    id: 13,
    firstName: "Amna",
    lastName: "Qureshi",
    category: "Intellectual Property",
    phone: "+92 312 6677882",
    email: "amna.qureshi@example.com",
    biography:
        "Amna Qureshi helps artists and inventors safeguard their intellectual creations and brands.",
    description: "Creative rights advocate and IP law specialist.",
    rating: 4.8,
    reviews: 156,
    profilePhoto: "https://randomuser.me/api/portraits/women/61.jpg",
  ),
  LawyerModel(
    id: 14,
    firstName: "Rehan",
    lastName: "Anwar",
    category: "Labor Law",
    phone: "+92 321 5566772",
    email: "rehan.anwar@example.com",
    biography:
        "Rehan Anwar assists organizations with employment contracts and labor disputes.",
    description: "Striving for fairness in the workplace through legal expertise.",
    rating: 4.4,
    reviews: 74,
    profilePhoto: "https://randomuser.me/api/portraits/men/21.jpg",
  ),
  LawyerModel(
    id: 15,
    firstName: "Maria",
    lastName: "Saeed",
    category: "Family Law",
    phone: "+92 310 6677883",
    email: "maria.saeed@example.com",
    biography:
        "Maria Saeed is a family law specialist helping clients with custody and adoption cases.",
    description: "Bringing empathy and experience to family legal issues.",
    rating: 4.6,
    reviews: 131,
    profilePhoto: "https://randomuser.me/api/portraits/women/39.jpg",
  ),
  LawyerModel(
    id: 16,
    firstName: "Taimoor",
    lastName: "Hassan",
    category: "Criminal Law",
    phone: "+92 300 4455667",
    email: "taimoor.hassan@example.com",
    biography:
        "Taimoor Hassan provides legal defense and civil litigation services across Punjab.",
    description: "Versatile lawyer with a reputation for diligence.",
    rating: 4.5,
    reviews: 115,
    profilePhoto: "https://randomuser.me/api/portraits/men/18.jpg",
  ),
  LawyerModel(
    id: 17,
    firstName: "Sana",
    lastName: "Nawaz",
    category: "Corporate Law",
    phone: "+92 321 8877664",
    email: "sana.nawaz@example.com",
    biography:
        "Sana Nawaz specializes in financial and banking law, helping clients with compliance and risk management.",
    description: "Empowering financial institutions with strong legal frameworks.",
    rating: 4.7,
    reviews: 99,
    profilePhoto: "https://randomuser.me/api/portraits/women/11.jpg",
  ),
  LawyerModel(
    id: 18,
    firstName: "Hamza",
    lastName: "Rashid",
    category: "Civil Law",
    phone: "+92 334 4433221",
    email: "hamza.rashid@example.com",
    biography:
        "Hamza Rashid is a civil law practitioner focusing on property and construction disputes.",
    description: "Reliable and efficient in handling real estate cases.",
    rating: 4.3,
    reviews: 68,
    profilePhoto: "https://randomuser.me/api/portraits/men/16.jpg",
  ),
  LawyerModel(
    id: 19,
    firstName: "Areeba",
    lastName: "Shahid",
    category: "Immigration Law",
    phone: "+92 312 2299881",
    email: "areeba.shahid@example.com",
    biography:
        "Areeba Shahid has successfully represented immigrants and asylum seekers globally.",
    description: "Dedicated to protecting the rights of migrants and refugees.",
    rating: 4.9,
    reviews: 213,
    profilePhoto: "https://randomuser.me/api/portraits/women/25.jpg",
  ),
  LawyerModel(
    id: 20,
    firstName: "Rizwan",
    lastName: "Aslam",
    category: "Cyber Law",
    phone: "+92 311 3344556",
    email: "rizwan.aslam@example.com",
    biography:
        "Rizwan Aslam provides expert legal solutions in technology, cybersecurity, and corporate compliance.",
    description: "Bridging the gap between law and modern digital systems.",
    rating: 4.6,
    reviews: 102,
    profilePhoto: "https://randomuser.me/api/portraits/men/48.jpg",
  ),
];
