final Map<String, dynamic> mockLawyerCasesData = {
  "status": 200,
  "data": {
    "pending_cases": [
      {
        "id": 1,
        "caseNo": "CR-501/2025",
        "title": "State vs Imran Ali",
        "court": "Lahore High Court",
        "status": "Evidence Examination",
        "client": "Imran Ali",
        "category": "Criminal",
        "appointmentType": "Walk-in",
        "winProbability": 0.78,
        "documents": [
          "FIR Copy",
          "Charge Sheet",
          "Witness Statements",
        ],
        "hearingDate": "14 Feb 2026",
      },
      {
        "id": 2,
        "caseNo": "CIV-212/2024",
        "title": "Land Dispute  Khan vs Malik",
        "court": "Islamabad Civil Court",
        "status": "Mediation Scheduled",
        "client": "Ahmed Khan",
        "category": "Civil",
        "appointmentType": "Video",
        "winProbability": 0.64,
        "documents": [
          "Sale Deed",
          "Fard Copy",
          "Site Photographs",
        ],
        "hearingDate": "03 Mar 2026",
      },
      {
        "id": 3,
        "caseNo": "CIV-330/2025",
        "title": "Minor Property Dispute – Raza vs Aslam",
        "court": "District Court, Lahore",
        "status": "Preliminary Hearing Scheduled",
        "client": "Muhammad Raza",
        "category": "Civil",
        "appointmentType": "Walk-in",
        "winProbability": 0.42,
        "documents": [
          "Initial Petition",
          "Site Plan",
        ],
        "hearingDate": "18 Feb 2026",
      },
    ],
    "disposed_cases": [
      {
        "id": 101,
        "caseNo": "CR-310/2023",
        "title": "Theft Case  State vs Bilal",
        "court": "Karachi Sessions Court",
        "status": "Disposed - Acquitted",
        "client": "Bilal Ahmed",
        "category": "Criminal",
        "appointmentType": "Walk-in",
        "winProbability": 0.0,
        "documents": [
          "Judgment Copy",
          "Final Arguments Notes",
        ],
        "disposedDate": "21 Sep 2025",
        "outcomeSummary": "Client fully acquitted. All charges dropped.",
      },
      {
        "id": 102,
        "caseNo": "CIV-890/2022",
        "title": "Contract Dispute  Ali Traders vs Prime Logistics",
        "court": "Lahore High Court",
        "status": "Disposed - Settled",
        "client": "Ali Traders",
        "category": "Civil",
        "appointmentType": "Video",
        "winProbability": 0.0,
        "documents": [
          "Settlement Agreement",
          "Final Order",
        ],
        "disposedDate": "10 Aug 2025",
        "outcomeSummary":
            "Favourable settlement achieved with full payment of outstanding dues.",
      },
    ],
  },
};
