final Map<String, dynamic> mockStudentCertificationsData = {
  "status": 200,
  "data": {
    "completed_certifications": [
      {
        "id": "1",
        "title": "Web Development Fundamentals",
        "description": "Learn the basics of HTML, CSS, and JavaScript",
        "startDate": "2024-01-15",
        "endDate": "2024-03-15",
        "certificateImage": "",
        "isCompleted": true,
        "duration": "2 months",
        "instructor": "John Smith",
        "level": "Beginner",
        "skills": ["HTML", "CSS", "JavaScript"],
      },
      {
        "id": "2",
        "title": "React.js Essentials",
        "description": "Master React fundamentals and build modern web applications",
        "startDate": "2024-02-01",
        "endDate": "2024-04-01",
        "certificateImage": "",
        "isCompleted": true,
        "duration": "2 months",
        "instructor": "Sarah Johnson",
        "level": "Intermediate",
        "skills": ["React", "Hooks", "State Management"],
      },
    ],
    "available_certifications": [
      {
        "id": "3",
        "title": "Python for Data Science",
        "description": "Learn Python programming for data analysis and machine learning",
        "startDate": "2024-03-01",
        "endDate": "2024-05-01",
        "certificateImage": "",
        "isCompleted": false,
        "duration": "2 months",
        "instructor": "Dr. Michael Chen",
        "level": "Intermediate",
        "skills": ["Python", "Pandas", "NumPy", "Matplotlib"],
      },
      {
        "id": "4",
        "title": "Mobile App Development with Flutter",
        "description": "Build cross-platform mobile applications using Flutter",
        "startDate": "2024-03-15",
        "endDate": "2024-05-15",
        "certificateImage": "",
        "isCompleted": false,
        "duration": "2 months",
        "instructor": "Emily Davis",
        "level": "Beginner",
        "skills": ["Flutter", "Dart", "Mobile UI", "State Management"],
      },
      {
        "id": "5",
        "title": "Cloud Computing with AWS",
        "description": "Master Amazon Web Services and cloud architecture",
        "startDate": "2024-04-01",
        "endDate": "2024-06-01",
        "certificateImage": "",
        "isCompleted": false,
        "duration": "2 months",
        "instructor": "Robert Wilson",
        "level": "Advanced",
        "skills": ["AWS", "EC2", "S3", "Lambda", "Cloud Architecture"],
      },
      {
        "id": "6",
        "title": "Machine Learning Fundamentals",
        "description": "Introduction to machine learning algorithms and applications",
        "startDate": "2024-04-15",
        "endDate": "2024-06-15",
        "certificateImage": "",
        "isCompleted": false,
        "duration": "2 months",
        "instructor": "Dr. Lisa Anderson",
        "level": "Advanced",
        "skills": ["ML Algorithms", "TensorFlow", "Scikit-learn", "Data Preprocessing"],
      },
    ],
  },
};
